/* ==========================================================
   OmniTalk PRO v12.0 — data.js
   Languages, phrasebooks, offline dictionaries, vocabulary.
========================================================== */

const LANGUAGES = [
  { code: 'my', name: 'Myanmar (Burmese)', flag: '🇲🇲', ttsLocale: 'my-MM', offline: true },
  { code: 'en', name: 'English', flag: '🇺🇸', ttsLocale: 'en-US', offline: true },
  { code: 'zh', name: 'Chinese (Mandarin)', flag: '🇨🇳', ttsLocale: 'zh-CN', offline: true },
  { code: 'th', name: 'Thai', flag: '🇹🇭', ttsLocale: 'th-TH', offline: true },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', ttsLocale: 'ja-JP', offline: false },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', ttsLocale: 'ko-KR', offline: false },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳', ttsLocale: 'vi-VN', offline: false },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', ttsLocale: 'hi-IN', offline: false },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩', ttsLocale: 'id-ID', offline: false },
  { code: 'ms', name: 'Malay', flag: '🇲🇾', ttsLocale: 'ms-MY', offline: false },
  { code: 'fil', name: 'Filipino (Tagalog)', flag: '🇵🇭', ttsLocale: 'fil-PH', offline: false },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦', ttsLocale: 'ar-SA', offline: false },
  { code: 'fr', name: 'French', flag: '🇫🇷', ttsLocale: 'fr-FR', offline: true },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', ttsLocale: 'es-ES', offline: true },
];

function langByCode(code){
  if(!code) return LANGUAGES[0];
  const c = code.toLowerCase().trim();
  return LANGUAGES.find(l => l.code === c || l.ttsLocale.toLowerCase().startsWith(c)) || LANGUAGES[0];
}

function langOptionLabel(l){
  return `${l.flag} ${l.name}`;
}

const PHRASEBOOK = [
  // 1. Emergency
  { cat: 'emergency', en: 'Help me please!', my: 'ကျေးဇူးပြု၍ ကူညီပါ!', zh: '请帮帮我！', th: 'ช่วยด้วยครับ/ค่ะ!' },
  { cat: 'emergency', en: 'Call the police immediately!', my: 'ရဲ အမြန်ခေါ်ပေးပါ!', zh: '快叫警察！', th: 'เรียกตำรวจด่วน!' },
  { cat: 'emergency', en: 'Call an ambulance!', my: 'လူနာတင်ယာဉ် ခေါ်ပေးပါ!', zh: '快叫救护车！', th: 'เรียกรถพยาบาล!' },
  { cat: 'emergency', en: 'There is a fire!', my: 'မီးလောင်နေတယ်!', zh: '着火了！', th: 'ไฟไหม้!' },
  { cat: 'emergency', en: 'I had an accident.', my: 'ကျွန်တော်/မ မတော်တဆမှု ဖြစ်ခဲ့ပါတယ်။', zh: '我发生了意外。', th: 'ฉันประสบอุบัติเหตุ' },
  { cat: 'emergency', en: 'I am lost, please help me.', my: 'လမ်းပျောက်နေလို့ ကူညီပေးပါခင်ဗျာ။', zh: '我迷路了，请帮帮我。', th: 'ฉันหลงทาง ช่วยหน่อยครับ/ค่ะ' },
  { cat: 'emergency', en: 'Where is the emergency exit?', my: 'အရေးပေါ် ထွက်ပေါက် ဘယ်မှာလဲ?', zh: '紧急出口在哪里？', th: 'ทางออกฉุกเฉินอยู่ที่ไหน?' },

  // 2. Workplace & Factory
  { cat: 'workplace', en: 'What is today’s task?', my: 'ဒီနေ့ လုပ်ရမယ့် အလုပ်က ဘာလဲခင်ဗျာ?', zh: '今天的任务是什么？', th: 'งานวันนี้คืออะไรครับ/ค่ะ?' },
  { cat: 'workplace', en: 'This machine is broken / not working.', my: 'ဒီစက် ပျက်နေပါတယ်/အလုပ်မလုပ်တော့ပါ။', zh: '这台机器坏了/不运转。', th: 'เครื่องนี้เสีย/ไม่ทำงานครับ' },
  { cat: 'workplace', en: 'Please check the defect rate.', my: 'ချို့ယွင်းချက် ရာခိုင်နှုန်းကို စစ်ဆေးပေးပါ။', zh: '请检查不良率。', th: 'กรุณาตรวจสอบอัตราของเสีย' },
  { cat: 'workplace', en: 'We need more raw materials.', my: 'ကုန်ကြမ်းပစ္စည်းတွေ ထပ်လိုပါတယ်။', zh: '我们需要更多原材料。', th: 'เราต้องการวัตถุดิบเพิ่ม' },
  { cat: 'workplace', en: 'Please wear safety helmet and gloves.', my: 'ဘေးကင်းလုံခြုံရေး ဦးထုပ်နှင့် လက်အိတ် ဝတ်ဆင်ပါ။', zh: '请戴好安全帽和手套。', th: 'กรุณาสวมหมวกนิรภัยและถุงมือ' },
  { cat: 'workplace', en: 'The production line is stopped.', my: 'ထုတ်လုပ်မှုလိုင်း ရပ်တန့်နေပါတယ်။', zh: '生产线暂停了。', th: 'สายการผลิตหยุดทำงาน' },
  { cat: 'workplace', en: 'I finished my assigned work.', my: 'ကျွန်တော် တာဝန်ကျအလုပ် ပြီးပါပြီ။', zh: '我完成了分配的工作。', th: 'ฉันทำงานที่ได้รับมอบหมายเสร็จแล้ว' },
  { cat: 'workplace', en: 'When does the shift end?', my: 'ဒီဂျူတီ ဘယ်အချိန် ပြီးမလဲခင်ဗျာ?', zh: '什么时候下班/换班？', th: 'กะนี้เลิกงานกี่โมงครับ?' },
  { cat: 'workplace', en: 'Be careful! Watch your hands.', my: 'သတိထားပါ! လက်ကို ဂရုစိုက်ပါ။', zh: '小心！注意手部安全。', th: 'ระวัง! ระวังมือด้วย' },
  { cat: 'workplace', en: 'Please explain how to operate this.', my: 'ဒါကို ဘယ်လိုမောင်းရမလဲ ရှင်းပြပေးပါ။', zh: '请解释一下如何操作。', th: 'ช่วยอธิบายวิธีใช้งานหน่อยครับ' },

  // 3. Medical & Health
  { cat: 'medical', en: 'I feel very sick.', my: 'ကျွန်တော်/မ နေမကောင်းဖြစ်နေပါတယ်။', zh: '我感觉很不舒服。', th: 'ฉันรู้สึกไม่สบายมาก' },
  { cat: 'medical', en: 'Where is the nearest hospital or clinic?', my: 'အနီးဆုံး ဆေးရုံ (သို့) ဆေးခန်း ဘယ်မှာလဲ?', zh: '最近的医院或诊所在哪里？', th: 'โรงพยาบาลหรือคลินิกที่ใกล้ที่สุดอยู่ที่ไหน?' },
  { cat: 'medical', en: 'I have severe abdominal pain.', my: 'ဗိုက် အရမ်းအောင့်/နာနေပါတယ်။', zh: '我肚子非常疼。', th: 'ฉันปวดท้องมาก' },
  { cat: 'medical', en: 'I have a high fever and headache.', my: 'အဖျားကြီးပြီး ခေါင်းကိုက်နေပါတယ်။', zh: '我发高烧且头痛。', th: 'ฉันมีไข้สูงและปวดหัว' },
  { cat: 'medical', en: 'I got injured at work.', my: 'အလုပ်မှာ ထိခိုက်ဒဏ်ရာ ရသွားပါတယ်။', zh: '我在工作中受伤了。', th: 'ฉันได้รับบาดเจ็บจากการทำงาน' },
  { cat: 'medical', en: 'I need pain relief medicine.', my: 'အကိုက်အခဲပျောက်ဆေး လိုအပ်ပါတယ်။', zh: '我需要止痛药。', th: 'ฉันต้องการยาแก้ปวด' },
  { cat: 'medical', en: 'I am allergic to this medicine.', my: 'ဒီဆေးနဲ့ ဓာတ်မတည့်ပါဘူး။', zh: '我对这种药过敏。', th: 'ฉันแพ้ยานี้' },
  { cat: 'medical', en: 'Can I take sick leave today?', my: 'ဒီနေ့ ဆေးခွင့် ယူလို့ရမလားခင်ဗျာ?', zh: '我今天可以请病假吗？', th: 'วันนี้ฉันขอลาป่วยได้ไหมครับ?' },

  // 4. Housing & Accommodation
  { cat: 'housing', en: 'Where is my dorm room?', my: 'ကျွန်တော့် အဆောင်အခန်း ဘယ်မှာလဲခင်ဗျာ?', zh: '我的宿舍房间在哪里？', th: 'ห้องพักหอพักของฉันอยู่ที่ไหน?' },
  { cat: 'housing', en: 'The water and electricity are cut off.', my: 'ရေ/မီး ပြတ်နေပါတယ်။', zh: '停水停电了。', th: 'น้ำและไฟดับครับ' },
  { cat: 'housing', en: 'The air conditioner is broken.', my: 'လေအေးပေးစက် (Aircon) ပျက်နေပါတယ်။', zh: '空调坏了。', th: 'เครื่องปรับอากาศเสีย' },
  { cat: 'housing', en: 'How much is the monthly room rent?', my: 'တစ်လ အခန်းခ ဘယ်လောက်လဲခင်ဗျာ?', zh: '每月房租是多少？', th: 'ค่าเช่าห้องเดือนละเท่าไหร่ครับ?' },
  { cat: 'housing', en: 'Where can I do laundry?', my: 'အဝတ် ဘယ်နားမှာ လျှော်လို့ရမလဲ?', zh: '在哪里可以洗衣服？', th: 'ซักผ้าได้ที่ไหนครับ?' },

  // 5. Wages & Overtime
  { cat: 'wages', en: 'When will the salary be paid?', my: 'လစာ ဘယ်နေ့ ထုတ်ပေးမှာလဲခင်ဗျာ?', zh: '什么时候发工资？', th: 'เงินเดือนจะออกวันไหนครับ?' },
  { cat: 'wages', en: 'Is overtime (OT) pay calculated correctly?', my: 'အချိန်ပိုကြေး (OT) တွက်ချက်မှု မှန်ကန်ရဲ့လားခင်ဗျာ?', zh: '加班费算得对吗？', th: 'คิดค่าล่วงเวลา (OT) ถูกต้องไหมครับ?' },
  { cat: 'wages', en: 'Can I work overtime today?', my: 'ဒီနေ့ OT ဆင်းလို့ရမလားခင်ဗျာ?', zh: '我今天可以加班吗？', th: 'วันนี้ฉันขอทำโอทีได้ไหมครับ?' },
  { cat: 'wages', en: 'Where is the nearest ATM?', my: 'အနီးဆုံး ATM ဘဏ်စက် ဘယ်မှာလဲ?', zh: '最近的ATM提款机在哪里？', th: 'ตู้ ATM ที่ใกล้ที่สุดอยู่ที่ไหน?' },
  { cat: 'wages', en: 'I want to transfer money home.', my: 'အိမ်ကို ငွေလွှဲချင်လို့ပါ။', zh: '我想往家里汇款。', th: 'ฉันต้องการโอนเงินกลับบ้าน' },

  // 6. Immigration & Visa
  { cat: 'immigration', en: 'Here is my passport and work permit.', my: 'ဒါ ကျွန်တော့် ပတ်စ်ပို့နဲ့ အလုပ်လုပ်ခွင့် ကတ်ပြားပါ။', zh: '这是我的护照和工作许可证。', th: 'นี่คือหนังสือเดินทางและใบอนุญาตทำงานของฉัน' },
  { cat: 'immigration', en: 'I need to renew my visa / contract.', my: 'ဗီဇာ (သို့) စာချုပ် သက်တမ်းတိုးဖို့ လိုအပ်ပါတယ်။', zh: '我需要续签签证/合同。', th: 'ฉันจำเป็นต้องต่ออายุวีซ่า/สัญญาจ้าง' },
  { cat: 'immigration', en: 'Where is the immigration office?', my: 'လဝက (Immigration) ရုံး ဘယ်မှာလဲခင်ဗျာ?', zh: '移民局在哪里？', th: 'สำนักงานตรวจคนเข้าเมืองอยู่ที่ไหน?' },
  { cat: 'immigration', en: 'Is this document legal and certified?', my: 'ဒီစာရွက်စာတမ်း တရားဝင် ခိုင်လုံရဲ့လားခင်ဗျာ?', zh: '这份文件合法且经过认证吗？', th: 'เอกสารนี้ถูกต้องตามกฎหมายหรือไม่?' },

  // 7. Daily Essentials & Conversational Idioms
  { cat: 'basics', en: 'Have you eaten rice / meal yet?', my: 'ထမင်းစားပြီးပြီလား?', zh: '你吃饭了吗？', th: 'กินข้าวหรือยังครับ/ค่ะ?' },
  { cat: 'basics', en: 'Hello / Greetings', my: 'မင်္ဂလာပါ', zh: '你好', th: 'สวัสดี' },
  { cat: 'basics', en: 'Thank you very much!', my: 'အများကြီး ကျေးဇူးတင်ပါတယ်!', zh: '非常感谢！', th: 'ขอบคุณมากครับ/ค่ะ!' },
  { cat: 'basics', en: 'I am sorry / Excuse me', my: 'တောင်းပန်ပါတယ် / ခွင့်လွှတ်ပါ', zh: '对不起 / 抱歉', th: 'ขอโทษครับ/ค่ะ' },
  { cat: 'basics', en: 'I understand clearly.', my: 'သေချာ နားလည်ပါပြီ။', zh: '我清楚明白了。', th: 'เข้าใจชัดเจนแล้วครับ' },
  { cat: 'basics', en: 'I do not understand, please repeat slowly.', my: 'နားမလည်ပါဘူး၊ ဖြည်းဖြည်းလေး ထပ်ပြောပေးပါ။', zh: '我不明白，请慢慢重复一遍。', th: 'ไม่เข้าใจครับ กรุณาพูดช้าๆ อีกครั้ง' },
  { cat: 'basics', en: 'Where is the restroom / toilet?', my: 'အိမ်သာ ဘယ်နားမှာလဲခင်ဗျာ?', zh: '洗手间/厕所在哪里？', th: 'ห้องน้ำอยู่ที่ไหนครับ?' },
  { cat: 'basics', en: 'How much is this?', my: 'ဒါ ဘယ်လောက်ကျပါသလဲခင်ဗျာ?', zh: '这个多少钱？', th: 'อันนี้ราคาเท่าไหร่ครับ?' },
  { cat: 'basics', en: 'Goodbye / See you later', my: 'သွားပါဦးမယ် / နောက်မှ တွေ့ကြမယ်', zh: '再见 / 回头见', th: 'ลาก่อน / ไว้เจอกันใหม่' },
  { cat: 'basics', en: 'What are you doing?', my: 'ဘာလုပ်နေတာလဲ?', zh: '你在做什么？', th: 'กำลังทำอะไรอยู่ครับ?' },
  { cat: 'basics', en: 'Where are you going?', my: 'ဘယ်သွားမလို့လဲ?', zh: '你要去哪里？', th: 'จะไปไหนครับ?' }
];

const PHRASES = [
  { en: 'Daniel David', my: 'ဒန်နီရယ် ဒေးဗစ်', zh: '丹尼尔·大卫', th: 'แดเนียล เดวิด' },
  { en: 'David', my: 'ဒေးဗစ်', zh: '大卫', th: 'เดวิด' },
  { en: 'Daniel', my: 'ဒန်နီရယ်', zh: '丹尼尔', th: 'แดเนียล' },
  { en: 'What are you doing', my: 'ဘာလုပ်နေတာလဲ', zh: '你在做什么', th: 'กำลังทำอะไรอยู่' },
  { en: 'Have you eaten', my: 'ထမင်းစားပြီးပြီလား', zh: '你吃了吗', th: 'กินข้าวหรือยัง' },
  { en: 'Hello', my: 'မင်္ဂလာပါ', zh: '你好', th: 'สวัสดี' },
  { en: 'Thank you', my: 'ကျေးဇူးတင်ပါတယ်', zh: '谢谢', th: 'ขอบคุณ' },
  { en: 'Yes', my: 'ဟုတ်ကဲ့ / ဟုတ်ပါတယ်', zh: '是的', th: 'ใช่' },
  { en: 'No', my: 'မဟုတ်ပါ / မဟုတ်ဘူး', zh: '不是 / 不', th: 'ไม่ใช่' },
  { en: 'Please', my: 'ကျေးဇူးပြု၍', zh: '请', th: 'กรุณာ' },
  { en: 'Sorry', my: 'တောင်းပန်ပါတယ်', zh: '对不起', th: 'ขอโทษ' }
];

/* Offline compositional vocabulary — ported from Walkie-Talkie Translator engine, used by offlineTranslate() for word-by-word matching when no exact/substring phrase matches. */
const WORDS = [
  {en:"I", my:"ငါ", zh:"我", th:"ฉัน", fr:"je", es:"yo"},
  {en:"you", my:"နင်", zh:"你", th:"คุณ", fr:"tu", es:"tú"},
  {en:"we", my:"ငါတို့", zh:"我们", th:"เรา", fr:"nous", es:"nosotros"},
  {en:"he", my:"သူ", zh:"他", th:"เขา", fr:"il", es:"él"},
  {en:"today", my:"ဒီနေ့", zh:"今天", th:"วันนี้", fr:"aujourd'hui", es:"hoy"},
  {en:"tomorrow", my:"မနက်ဖြန်", zh:"明天", th:"พรุ่งนี้", fr:"demain", es:"mañana"},
  {en:"yesterday", my:"မနေ့က", zh:"昨天", th:"เมื่อวาน", fr:"hier", es:"ayer"},
  {en:"now", my:"အခု", zh:"现在", th:"ตอนนี้", fr:"maintenant", es:"ahora"},
  {en:"later", my:"နောက်မှ", zh:"稍后", th:"ทีหลัง", fr:"plus tard", es:"más tarde"},
  {en:"good", my:"ကောင်းတယ်", zh:"好", th:"ดี", fr:"bon", es:"bueno"},
  {en:"bad", my:"မကောင်းဘူး", zh:"不好", th:"ไม่ดี", fr:"mauvais", es:"malo"},
  {en:"big", my:"ကြီးတယ်", zh:"大", th:"ใหญ่", fr:"grand", es:"grande"},
  {en:"small", my:"သေးတယ်", zh:"小", th:"เล็ก", fr:"petit", es:"pequeño"},
  {en:"hot", my:"ပူတယ်", zh:"热", th:"ร้อน", fr:"chaud", es:"caliente"},
  {en:"cold", my:"အေးတယ်", zh:"冷", th:"หนาว", fr:"froid", es:"frío"},
  {en:"water", my:"ရေ", zh:"水", th:"น้ำ", fr:"eau", es:"agua"},
  {en:"food", my:"အစားအစာ", zh:"食物", th:"อาหาร", fr:"nourriture", es:"comida"},
  {en:"money", my:"ငွေ", zh:"钱", th:"เงิน", fr:"argent", es:"dinero"},
  {en:"work", my:"အလုပ်", zh:"工作", th:"งาน", fr:"travail", es:"trabajo"},
  {en:"home", my:"အိမ်", zh:"家", th:"บ้าน", fr:"maison", es:"casa"},
  {en:"go", my:"သွားတယ်", zh:"去", th:"ไป", fr:"aller", es:"ir"},
  {en:"come", my:"လာတယ်", zh:"来", th:"มา", fr:"venir", es:"venir"},
  {en:"eat", my:"စားတယ်", zh:"吃", th:"กิน", fr:"manger", es:"comer"},
  {en:"drink", my:"သောက်တယ်", zh:"喝", th:"ดื่ม", fr:"boire", es:"beber"},
  {en:"sleep", my:"အိပ်တယ်", zh:"睡觉", th:"นอน", fr:"dormir", es:"dormir"},
  {en:"buy", my:"ဝယ်တယ်", zh:"买", th:"ซื้อ", fr:"acheter", es:"comprar"},
  {en:"sell", my:"ရောင်းတယ်", zh:"卖", th:"ขาย", fr:"vendre", es:"vender"},
  {en:"open", my:"ဖွင့်တယ်", zh:"开", th:"เปิด", fr:"ouvrir", es:"abrir"},
  {en:"close", my:"ပိတ်တယ်", zh:"关", th:"ปิด", fr:"fermer", es:"cerrar"},
  {en:"fast", my:"မြန်တယ်", zh:"快", th:"เร็ว", fr:"rapide", es:"rápido"},
  {en:"slow", my:"နှေးတယ်", zh:"慢", th:"ช้า", fr:"lent", es:"lento"},
  {en:"one", my:"တစ်", zh:"一", th:"หนึ่ง", fr:"un", es:"uno"},
  {en:"two", my:"နှစ်", zh:"二", th:"สอง", fr:"deux", es:"dos"},
  {en:"three", my:"သုံး", zh:"三", th:"สาม", fr:"trois", es:"tres"},
  {en:"many", my:"များများ", zh:"很多", th:"เยอะ", fr:"beaucoup", es:"muchos"},
  {en:"here", my:"ဒီမှာ", zh:"这里", th:"ที่นี่", fr:"ici", es:"aquí"},
  {en:"there", my:"အဲ့မှာ", zh:"那里", th:"ที่นั่น", fr:"là-bas", es:"allí"},
  {en:"what", my:"ဘာ", zh:"什么", th:"อะไร", fr:"quoi", es:"qué"},
  {en:"who", my:"ဘယ်သူ", zh:"谁", th:"ใคร", fr:"qui", es:"quién"},
  {en:"why", my:"ဘာကြောင့်", zh:"为什么", th:"ทำไม", fr:"pourquoi", es:"por qué"},
  {en:"how", my:"ဘယ်လို", zh:"怎么", th:"อย่างไร", fr:"comment", es:"cómo"},
  {en:"please", my:"ကျေးဇူးပြု၍", zh:"请", th:"กรุณา", fr:"s'il vous plaît", es:"por favor"},
  {en:"thanks", my:"ကျေးဇူးတင်ပါတယ်", zh:"谢谢", th:"ขอบคุณ", fr:"merci", es:"gracias"},
  {en:"sorry", my:"တောင်းပန်ပါတယ်", zh:"对不起", th:"ขอโทษ", fr:"désolé", es:"lo siento"},
  {en:"yes", my:"ဟုတ်ကဲ့", zh:"是", th:"ใช่", fr:"oui", es:"sí"},
  {en:"no", my:"မဟုတ်ဘူး", zh:"不", th:"ไม่", fr:"non", es:"no"},
  {en:"want", my:"လိုချင်တယ်", zh:"想要", th:"ต้องการ", fr:"vouloir", es:"querer"},
  {en:"need", my:"လိုအပ်တယ်", zh:"需要", th:"จำเป็น", fr:"avoir besoin", es:"necesitar"},
  {en:"tired", my:"ပင်ပန်းတယ်", zh:"累", th:"เหนื่อย", fr:"fatigué", es:"cansado"},
  {en:"happy", my:"ပျော်တယ်", zh:"开心", th:"มีความสุข", fr:"heureux", es:"feliz"},
  {en:"sad", my:"ဝမ်းနည်းတယ်", zh:"难过", th:"เศร้า", fr:"triste", es:"triste"},
  {en:"angry", my:"စိတ်ဆိုးတယ်", zh:"生气", th:"โกรธ", fr:"en colère", es:"enojado"},
  {en:"sick", my:"နေမကောင်းဘူး", zh:"生病", th:"ป่วย", fr:"malade", es:"enfermo"},
  {en:"friend", my:"သူငယ်ချင်း", zh:"朋友", th:"เพื่อน", fr:"ami", es:"amigo"},
  {en:"family", my:"မိသားစု", zh:"家人", th:"ครอบครัว", fr:"famille", es:"familia"},
  {en:"time", my:"အချိန်", zh:"时间", th:"เวลา", fr:"temps", es:"tiempo"},
  {en:"day", my:"နေ့", zh:"天", th:"วัน", fr:"jour", es:"día"},
  {en:"morning", my:"မနက်", zh:"早上", th:"เช้า", fr:"matin", es:"mañana"},
  {en:"evening", my:"ညနေ", zh:"晚上", th:"เย็น", fr:"soir", es:"tarde"},
  {en:"night", my:"ညဘက်", zh:"夜晚", th:"กลางคืน", fr:"nuit", es:"noche"},
  {en:"finish", my:"ပြီးတယ်", zh:"完成", th:"เสร็จ", fr:"finir", es:"terminar"},
  {en:"start", my:"စတယ်", zh:"开始", th:"เริ่ม", fr:"commencer", es:"empezar"},
  {en:"wait", my:"စောင့်တယ်", zh:"等", th:"รอ", fr:"attendre", es:"esperar"},
  {en:"help", my:"ကူညီတယ်", zh:"帮助", th:"ช่วยเหลือ", fr:"aider", es:"ayudar"},
  {en:"problem", my:"ပြဿနာ", zh:"问题", th:"ปัญหา", fr:"problème", es:"problema"},
  {en:"correct", my:"မှန်တယ်", zh:"正确", th:"ถูกต้อง", fr:"correct", es:"correcto"},
  {en:"wrong", my:"မှားတယ်", zh:"错误", th:"ผิด", fr:"faux", es:"incorrecto"},
  {en:"four", my:"လေး", zh:"四", th:"สี่", fr:"quatre", es:"cuatro"},
  {en:"five", my:"ငါး", zh:"五", th:"ห้า", fr:"cinq", es:"cinco"},
  {en:"six", my:"ခြောက်", zh:"六", th:"หก", fr:"six", es:"seis"},
  {en:"seven", my:"ခုနှစ်", zh:"七", th:"เจ็ด", fr:"sept", es:"siete"},
  {en:"eight", my:"ရှစ်", zh:"八", th:"แปด", fr:"huit", es:"ocho"},
  {en:"nine", my:"ကိုး", zh:"九", th:"เก้า", fr:"neuf", es:"nueve"},
  {en:"ten", my:"ဆယ်", zh:"十", th:"สิบ", fr:"dix", es:"diez"},
  {en:"hundred", my:"ရာ", zh:"百", th:"ร้อย", fr:"cent", es:"cien"},
  {en:"thousand", my:"ထောင်", zh:"千", th:"พัน", fr:"mille", es:"mil"},
  {en:"Monday", my:"တနင်္လာနေ့", zh:"星期一", th:"วันจันทร์", fr:"lundi", es:"lunes"},
  {en:"Tuesday", my:"အင်္ဂါနေ့", zh:"星期二", th:"วันอังคาร", fr:"mardi", es:"martes"},
  {en:"Wednesday", my:"ဗုဒ္ဓဟူးနေ့", zh:"星期三", th:"วันพุธ", fr:"mercredi", es:"miércoles"},
  {en:"Thursday", my:"ကြာသပတေးနေ့", zh:"星期四", th:"วันพฤหัสบดี", fr:"jeudi", es:"jueves"},
  {en:"Friday", my:"သောကြာနေ့", zh:"星期五", th:"วันศุกร์", fr:"vendredi", es:"viernes"},
  {en:"Saturday", my:"စနေနေ့", zh:"星期六", th:"วันเสาร์", fr:"samedi", es:"sábado"},
  {en:"Sunday", my:"တနင်္ဂနွေနေ့", zh:"星期天", th:"วันอาทิตย์", fr:"dimanche", es:"domingo"},
  {en:"salary", my:"လစာ", zh:"工资", th:"เงินเดือน", fr:"salaire", es:"salario"},
  {en:"overtime", my:"အချိန်ပို", zh:"加班", th:"ทำงานล่วงเวลา", fr:"heures supplémentaires", es:"horas extras"},
  {en:"boss", my:"အထက်လူကြီး", zh:"老板", th:"เจ้านาย", fr:"patron", es:"jefe"},
  {en:"contract", my:"စာချုပ်", zh:"合同", th:"สัญญา", fr:"contrat", es:"contrato"},
  {en:"passport", my:"နိုင်ငံကူးလက်မှတ်", zh:"护照", th:"หนังสือเดินทาง", fr:"passeport", es:"pasaporte"},
  {en:"police", my:"ရဲ", zh:"警察", th:"ตำรวจ", fr:"police", es:"policía"},
  {en:"hospital", my:"ဆေးရုံ", zh:"医院", th:"โรงพยาบาล", fr:"hôpital", es:"hospital"},
  {en:"doctor", my:"ဆရာဝန်", zh:"医生", th:"หมอ", fr:"médecin", es:"médico"},
  {en:"medicine", my:"ဆေးဝါး", zh:"药", th:"ยา", fr:"médicament", es:"medicina"},
  {en:"pain", my:"နာကျင်မှု", zh:"疼痛", th:"อาการปวด", fr:"douleur", es:"dolor"},
  {en:"injury", my:"ဒဏ်ရာ", zh:"受伤", th:"บาดเจ็บ", fr:"blessure", es:"lesión"},
  {en:"blood", my:"သွေး", zh:"血", th:"เลือด", fr:"sang", es:"sangre"},
  {en:"fever", my:"အဖျား", zh:"发烧", th:"ไข้", fr:"fièvre", es:"fiebre"},
  {en:"emergency", my:"အရေးပေါ်", zh:"紧急情况", th:"เหตุฉุกเฉิน", fr:"urgence", es:"emergencia"},
  {en:"ambulance", my:"လူနာတင်ကား", zh:"救护车", th:"รถพยาบาล", fr:"ambulance", es:"ambulancia"},
  {en:"rent", my:"အိမ်ငှားခ", zh:"房租", th:"ค่าเช่า", fr:"loyer", es:"alquiler"},
  {en:"landlord", my:"အိမ်ရှင်", zh:"房东", th:"เจ้าของบ้าน", fr:"propriétaire", es:"propietario"},
  {en:"electricity", my:"မီးလျှပ်စစ်", zh:"电", th:"ไฟฟ้า", fr:"électricité", es:"electricidad"},
  {en:"danger", my:"အန္တရာယ်", zh:"危险", th:"อันตราย", fr:"danger", es:"peligro"},
  {en:"safe", my:"ဘေးကင်းတယ်", zh:"安全", th:"ปลอดภัย", fr:"sûr", es:"seguro"},
  {en:"machine", my:"စက်ပစ္စည်း", zh:"机器", th:"เครื่องจักร", fr:"machine", es:"máquina"},
  {en:"document", my:"စာရွက်စာတမ်း", zh:"文件", th:"เอกสาร", fr:"document", es:"documento"},
  {en:"signature", my:"လက်မှတ်", zh:"签名", th:"ลายเซ็น", fr:"signature", es:"firma"},
];
